# Generated by Django 5.2.6 on 2025-09-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                ("release_date", models.DateField(verbose_name="Дата выхода продукта на рынок")),
            ],
        ),
        migrations.CreateModel(
            name="ProductSupplierRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.product")),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование поставщика")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                ("street", models.CharField(max_length=255, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=10, verbose_name="Номер дома")),
                ("debt_to_parent", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_supplier",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="e_shop.supplier"),
                ),
                ("products", models.ManyToManyField(through="e_shop.ProductSupplierRelation", to="e_shop.product")),
            ],
        ),
        migrations.AddField(
            model_name="productsupplierrelation",
            name="supplier",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.supplier"),
        ),
    ]
