# Generated by Django 5.2.6 on 2025-09-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productsupplierrelation",
            options={"verbose_name": "Отношение Товара-Поставщика", "verbose_name_plural": "Отношения Товаров-Поставщиков"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики"},
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название товара"),
        ),
        migrations.AlterField(
            model_name="productsupplierrelation",
            name="added_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления"),
        ),
        migrations.AlterField(
            model_name="productsupplierrelation",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.product", verbose_name="Товар"),
        ),
        migrations.AlterField(
            model_name="productsupplierrelation",
            name="supplier",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.supplier", verbose_name="Поставщик"),
        ),
    ]
